version: "3.8"

services:

  db-service:
    build: ./apps/db-service
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - ${DB_SERVICE_PORT}:${DB_SERVICE_PORT}

  postgres:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-checkpointer:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${LANGGRAPH_RECEIPT_DB_USER}
      - POSTGRES_PASSWORD=${LANGGRAPH_RECEIPT_DB_PASSWORD}
      - POSTGRES_DB=${LANGGRAPH_RECEIPT_DB_NAME}
    volumes:
      - ./checkpointer_receipt_data:/var/lib/postgresql/data
    ports:
      - ${LANGGRAPH_RECEIPT_DB_PORT_EXTERNAL}:${LANGGRAPH_RECEIPT_DB_PORT_INTERNAL}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${LANGGRAPH_RECEIPT_DB_USER} -d ${LANGGRAPH_RECEIPT_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  postgres-room-checkpointer:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${LANGGRAPH_ROOM_DB_USER}
      - POSTGRES_PASSWORD=${LANGGRAPH_ROOM_DB_PASSWORD}
      - POSTGRES_DB=${LANGGRAPH_ROOM_DB_NAME}
    volumes:
      - ./checkpointer_room_data:/var/lib/postgresql/data
    ports:
      - ${LANGGRAPH_ROOM_DB_PORT_EXTERNAL}:${LANGGRAPH_ROOM_DB_PORT_INTERNAL}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${LANGGRAPH_ROOM_DB_USER} -d ${LANGGRAPH_ROOM_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s


  executor-service:
    build: ./apps/executor-service
    env_file:
      - .env
    ports:
      - ${EXEC_SERVICE_PORT}:${EXEC_SERVICE_PORT}
    volumes:
      - ./apps/executor-service/app:/app/app
    depends_on:
      postgres-checkpointer:
        condition: service_healthy
      postgres-room-checkpointer:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${EXEC_SERVICE_PORT}/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s